import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ background: 'var(--primary-green)', color: 'white', padding: '1.5rem 0', textAlign: 'center' }}>
          <h1 style={{ margin: 0, fontSize: '2.5rem', letterSpacing: '2px' }}>Gilead International Group of Schools</h1>
          <p style={{ margin: 0, fontSize: '1.2rem', fontStyle: 'italic', color: 'var(--accent-green)' }}>
            Knowledge and Power
          </p>
          <nav style={{ marginTop: '1rem' }}>
            <a href="/" style={{ margin: '0 1rem', color: 'white', fontWeight: 'bold' }}>Home</a>
            <a href="/about" style={{ margin: '0 1rem', color: 'white' }}>About</a>
            <a href="/admissions" style={{ margin: '0 1rem', color: 'white' }}>Admissions</a>
            <a href="/careers" style={{ margin: '0 1rem', color: 'white' }}>Careers</a>
            <a href="/gallery" style={{ margin: '0 1rem', color: 'white' }}>Gallery</a>
            <a href="/contact" style={{ margin: '0 1rem', color: 'white' }}>Contact</a>
          </nav>
        </header>
        <main style={{ minHeight: '80vh', background: 'var(--background)' }}>{children}</main>
      </body>
    </html>
  );
}
